#!/usr/bin/env bash
# commit.sh — 対象を明示したコミット（提供コマンド）
# 仕様: .claude/docs/10_spec/skills/20-common-step-commit-push.md「commit.sh」
# 使い方: bash .claude/skills/20-common-step-commit-push/scripts/commit.sh -m "<メッセージ>" [--allow-empty] <ファイル>...
#   オプションは順不同。パスはリポジトリルート相対。
# 終了コード: 成功 0 / 検査未充足 1 / 引数や環境の誤り 2。最終行は `OK: ...` または `CP<番号>: ...`
set -euo pipefail

# 共通ライブラリの読み込み行（20-common-step-shell-script 仕様「読み込み行」が正）。引数 <lib> <policy> だけを変え、中身を改変しない。
# shellcheck disable=SC1090,SC2317
__ss_load() { local lib="$1" pol="$2" d="${BASH_SOURCE[1]%/*}" r="" f=""; [ "$d" = "${BASH_SOURCE[1]}" ] && d="."; case "$d" in /*|[A-Za-z]:/*) ;; *) d="$PWD/$d" ;; esac; while [ -n "$d" ] && [ ! -d "$d/.claude" ]; do case "$d" in */*) d="${d%/*}" ;; *) d="" ;; esac; done; r="$d"; f="$r/.claude/skills/20-common-step-shell-script/scripts/$lib.sh"; if [ ! -f "$f" ] && [ -n "${CLAUDE_PROJECT_DIR:-}" ]; then r="${CLAUDE_PROJECT_DIR//\\//}"; f="$r/.claude/skills/20-common-step-shell-script/scripts/$lib.sh"; fi; if [ ! -f "$f" ] && command -v git >/dev/null 2>&1; then r="$(git rev-parse --show-toplevel 2>/dev/null || true)"; f="$r/.claude/skills/20-common-step-shell-script/scripts/$lib.sh"; fi; if [ -n "$r" ] && [ -f "$f" ]; then LOGGER_ROOT="$r"; export LOGGER_ROOT; . "$f"; return 0; fi; case "$pol" in nop) LOGGER_ROOT="${r:-$PWD}"; export LOGGER_ROOT; log_debug() { :; }; log_info() { :; }; log_warn() { :; }; log_error() { :; }; fm_extract() { FM_BLOCK=""; return 1; }; fm_get() { return 1; }; fm_list() { return 1; }; fm_has() { return 1; } ;; deny) printf '%s\n' "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"${HOOK_DENY_ID:-WF009}: 機構の不調 — 共通ライブラリ $lib を読み込めない（リポジトリルート未解決）\"}}"; exit 0 ;; *) printf '%s\n' "FATAL: 共通ライブラリ $lib を読み込めない（リポジトリルート未解決）"; exit 2 ;; esac; }
__ss_load logger nop

readonly SCRIPT_PREFIX="CP"
readonly EXCLUDE_FILE=".claude/skills/20-common-step-commit-push/assets/exclude-patterns.txt"
readonly MESSAGE_RE='^(feat|fix|docs|chore|refactor|test|perf|build|ci|ai-asset): .+$'
# AI 生成を示すフッター・モデル名（大文字小文字を区別しない）。本文の語としての「Claude Code」等は対象にせず、フッター形と機械的なモデル名だけを見る
readonly FOOTER_RE='(co-authored-by:|generated with|generated by|signed-off-by:.*(claude|anthropic|openai)|noreply@anthropic\.com|🤖|claude-(opus|sonnet|haiku|fable|mythos)[-0-9.]*|claude (opus|sonnet|haiku|fable|mythos) [0-9]|gpt-[0-9]|chatgpt|github copilot|gemini-[0-9])'

usage() {
  cat <<'USAGE'
使い方: bash .claude/skills/20-common-step-commit-push/scripts/commit.sh -m "<メッセージ>" [--allow-empty] <ファイル>...
  -m <メッセージ>   `<prefix>: <日本語 1 行>`（prefix: feat fix docs chore refactor test perf build ci ai-asset）
  --allow-empty     差分が無くてもコミットする（MR 作成時の空コミットのみ）
  <ファイル>...     コミットする対象（リポジトリルート相対）。-A / . / glob は受け付けない
USAGE
}

EXCLUDED=()   # "<path>（<pattern>）"
print_excluded() {
  if [ "${#EXCLUDED[@]}" -eq 0 ]; then printf '除外: なし\n'; else printf '除外: %s\n' "$(IFS=,; printf '%s' "${EXCLUDED[*]}")"; fi
}
result_ok() { # $1=メッセージ
  log_info "OK: $1"
  printf 'OK: %s\n' "$1"
  exit 0
}
result_ng() { # $1=番号 $2=メッセージ $3=終了コード
  log_warn "${SCRIPT_PREFIX}$1: $2"
  printf '%s%s: %s\n' "$SCRIPT_PREFIX" "$1" "$2"
  exit "$3"
}

# 除外パターンに一致すればパターンを REPLY に入れて 0
matches_exclude() { # $1=パス
  local path="$1" base="${1##*/}" pat
  REPLY=""
  [ -f "$EXCLUDE_FILE" ] || return 1
  while IFS= read -r pat || [ -n "$pat" ]; do
    pat="${pat%$'\r'}"
    pat="${pat#"${pat%%[![:space:]]*}"}"
    [ -z "$pat" ] && continue
    case "$pat" in \#*) continue ;; esac
    # shellcheck disable=SC2053
    if [[ "$pat" == */* ]]; then
      [[ "$path" == $pat ]] && { REPLY="$pat"; return 0; }
    else
      [[ "$base" == $pat ]] && { REPLY="$pat"; return 0; }
    fi
  done < "$EXCLUDE_FILE"
  return 1
}

main() {
  local message="" allow_empty=0 files=() f
  # 1. 引数（順不同）
  while [ $# -gt 0 ]; do
    case "$1" in
      -h|--help) usage; exit 0 ;;
      -m)
        [ $# -ge 2 ] || result_ng 001 "-m にメッセージが無い（引数の誤り。期待する形式: -m \"<prefix>: <日本語 1 行>\"）" 2
        message="$2"; shift ;;
      -m*) message="${1#-m}" ;;
      --allow-empty) allow_empty=1 ;;
      -A|--all|-a|.|./|..) result_ng 001 "一括指定（$1）は受け付けない。自分が変更したファイルだけをパスで明示する" 2 ;;
      --amend|--no-verify) result_ng 001 "$1 は存在しないオプション（直前コミットの書き換え・検査の回避はしない）" 2 ;;
      -*) result_ng 001 "不明なオプション: $1（-m <メッセージ> / --allow-empty / <ファイル>...）" 2 ;;
      *)
        case "$1" in
          *'*'*|*'?'*|*'['*) result_ng 001 "glob（$1）は受け付けない。パスを 1 つずつ明示する" 2 ;;
        esac
        f="${1#./}"
        # ディレクトリ（symlink 経由を含む）は受け付けない。除外パターンは指定されたパスにしか当たらず、中の .env 等を見落とすため
        if [ -d "$f" ]; then result_ng 001 "ディレクトリ（$f）は受け付けない。除外パターンはファイル単位で当たるので、中のファイルをパスで明示する" 2; fi
        files+=("$f") ;;
    esac
    shift
  done

  cd "$LOGGER_ROOT" || result_ng 001 "リポジトリルートに移動できない: $LOGGER_ROOT" 2
  log_info "start message='${message}' files=${files[*]:-} allow_empty=$allow_empty"

  # 1. メッセージの検査
  [ -n "$message" ] || result_ng 002 "メッセージが無い。期待する形式: <prefix>: <日本語 1 行>（prefix: feat fix docs chore refactor test perf build ci ai-asset）" 1
  case "$message" in *$'\n'*) result_ng 002 "メッセージは 1 行にする（改行を含む）。期待する形式: <prefix>: <日本語 1 行>" 1 ;; esac
  [[ "$message" =~ $MESSAGE_RE ]] || result_ng 002 "メッセージ規約違反: '$message'。期待する形式: <prefix>: <日本語 1 行>（prefix: feat fix docs chore refactor test perf build ci ai-asset）" 1
  local lower="${message,,}"
  if [[ "$lower" =~ $FOOTER_RE ]]; then
    result_ng 002 "AI 生成を示すフッター・モデル名を含む（検出: '${BASH_REMATCH[0]}'）。期待する形式: <prefix>: <日本語 1 行> のみ" 1
  fi

  # 2. 対象の検査
  if [ "${#files[@]}" -eq 0 ] && [ "$allow_empty" -eq 0 ]; then
    result_ng 001 "対象ファイルが未指定。自分が変更したファイルだけをパスで明示する（空コミットは --allow-empty）" 2
  fi

  # 3. 除外パターン
  local kept=()
  for f in "${files[@]}"; do
    if matches_exclude "$f"; then EXCLUDED+=("$f（$REPLY）"); else kept+=("$f"); fi
  done
  if [ "${#files[@]}" -gt 0 ] && [ "${#kept[@]}" -eq 0 ]; then
    print_excluded
    result_ng 003 "対象がすべて除外パターンに一致した（${EXCLUDED[*]}）。除外パターンは $EXCLUDE_FILE" 1
  fi

  # 4. ステージと差分の検査
  local add_err
  if [ "${#kept[@]}" -gt 0 ]; then
    if ! add_err="$(git add -- "${kept[@]}" 2>&1)"; then
      print_excluded
      printf '%s\n' "$add_err"
      result_ng 001 "git がステージできないパスがある（未追跡のまま削除・綴り誤り・.gitignore 対象）。上の git の出力を確認する" 2
    fi
    # 実際にステージされたパスに除外パターンを当て直す（指定と実パスが異なる経路の保険）。一致があれば index から戻して止まる
    local staged_ng=() s
    while IFS= read -r s; do
      [ -n "$s" ] || continue
      if matches_exclude "$s"; then git reset -q -- "$s" >/dev/null 2>&1 || true; staged_ng+=("$s（$REPLY）"); fi
    done < <(git diff --cached --name-only -- "${kept[@]}" | tr -d '\r')
    if [ "${#staged_ng[@]}" -gt 0 ]; then
      EXCLUDED+=("${staged_ng[@]}")
      print_excluded
      result_ng 003 "ステージされたパスに除外パターンの一致がある（${staged_ng[*]}）。index から戻した。対象を見直す" 1
    fi
    if git diff --cached --quiet -- "${kept[@]}" && [ "$allow_empty" -eq 0 ]; then
      print_excluded
      result_ng 004 "差分が無い（${kept[*]}）。空コミットは --allow-empty（MR 作成時のみ）に限る" 1
    fi
  fi

  # 5. コミット（amend・--no-verify に相当するオプションは持たない）
  local out sha committed
  local args=(commit -q -m "$message")
  [ "$allow_empty" -eq 1 ] && args+=(--allow-empty)
  if [ "${#kept[@]}" -gt 0 ]; then
    if ! out="$(git "${args[@]}" -- "${kept[@]}" 2>&1)"; then
      print_excluded
      printf '%s\n' "$out"
      result_ng 004 "git commit が失敗した（コミット時の検査・フック）。上の出力を確認する" 1
    fi
  else
    if ! out="$(git "${args[@]}" 2>&1)"; then
      print_excluded
      printf '%s\n' "$out"
      result_ng 004 "git commit が失敗した（コミット時の検査・フック）。上の出力を確認する" 1
    fi
  fi

  # 6. 出力
  sha="$(git rev-parse --short HEAD)"
  committed="$(git show --pretty=format: --name-status HEAD | sed '/^$/d')"
  printf 'コミット %s: %s\n' "$sha" "$message"
  [ -n "$committed" ] && printf '%s\n' "$committed"
  print_excluded
  local n
  n="$(printf '%s\n' "$committed" | sed '/^$/d' | wc -l | tr -d ' ')"
  log_info "committed sha=$sha files=$n excluded=${#EXCLUDED[@]}"
  result_ok "${n} ファイルをコミットした（${sha}）。除外: $([ "${#EXCLUDED[@]}" -eq 0 ] && printf 'なし' || printf '%s' "${EXCLUDED[*]}")"
}

main "$@"
